---
services:
  db:
    image: postgres:latest
    restart: always
    shm_size: 512mb
    ports:
      - 5432:5432
    volumes:
      - ./.pg-volume:/var/lib/postgresql
      - ./../contrib/database/schema:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: "resource-nexus"
      POSTGRES_USER: "resource-nexus"
      POSTGRES_DB: "resource-nexus"
